# Ma_Sys.ma CI 1.0.0, Copyright (c) 2019, 2020 Ma_Sys.ma.
# For further info send an e-mail to Ma_Sys.ma@web.de.
#
# This file defines a suggested set of containers to use for building packages
# for multiple CPU architectures in addition to running a "main" CI instance.

version: "2.1"
services:
    amd64:
        image: masysmaci:latest
        build:
            context: .
            dockerfile: dockerfile_masysmaci
            args:
                - MA_DEBIAN_MIRROR=${MA_DEBIAN_MIRROR:-http://ftp.de.debian.org/debian}
        volumes:
            - ../:/home/masysmaci/root
            # As of now, it seems one cannot use :ro here, because gpg needs
            # write access for signing (WTF), see also:
            # http://gnupg.10057.n7.nabble.com/gnupg-on-read-only-filesystem-td53632.html
            - ${MA_GNUPG_ROOT:-./dot_gnupg_sample/}:/home/masysmaci/.gnupg
            - ${MA_REPOSITORY_ROOT:-/var/tmp/masysmacirepo}:/data/programs/repo:Z
        command:
            - /home/masysmaci/root/co-ci/masysmaci.pl
        ports:
            - 127.0.0.1:9030:9030
    i386:
        image: i386/masysmaci:latest
        build:
            context: .
            dockerfile: dockerfile_masysmaci
            args:
                - MDVL_CI_ARCH_PREFIX=i386/
                - MA_DEBIAN_MIRROR=${MA_DEBIAN_MIRROR:-http://ftp.de.debian.org/debian}
        volumes:
            - ./dot_ssh_i386:/home/masysmaci/.ssh:ro
            - ../:/home/masysmaci/root
    armhf:
        image: arm32v7/masysmaci:latest
        build:
            context: .
            dockerfile: dockerfile_masysmaci
            args:
                - MDVL_CI_ARCH_PREFIX=arm32v7/
                - MA_DEBIAN_MIRROR=${MA_DEBIAN_MIRROR:-http://ftp.de.debian.org/debian}
        volumes:
            - ./dot_ssh_armhf:/home/masysmaci/.ssh:ro
            - ../:/home/masysmaci/root
