# docker build -t masysmaci -f dockerfile_masysmaci .
# docker build -t i386/masysmaci -f dockerfile_masysmaci --build-arg=MDVL_CI_ARCH_PREFIX=i386/ .
# docker build -t armhf/masysmaci -f dockerfile_masysmaci --build=arg=MDVL_CI_ARCH_PREFIX=armhf/ .

ARG MDVL_CI_ARCH_PREFIX=
ARG MDVL_CI_DEBIAN_VERSION=buster
FROM debian:$MDVL_CI_DEBIAN_VERSION AS qemustatic
ARG MDVL_CI_DEBIAN_VERSION=buster
ARG MA_DEBIAN_MIRROR=http://ftp.it.debian.org/debian
SHELL ["/bin/sh", "-ec"]
RUN     :; \
	printf "%s\n%s\n%s %s\n" \
		"deb $MA_DEBIAN_MIRROR $MDVL_CI_DEBIAN_VERSION main" \
		"deb $MA_DEBIAN_MIRROR $MDVL_CI_DEBIAN_VERSION-updates main" \
		"deb http://security.debian.org/" \
					"$MDVL_CI_DEBIAN_VERSION/updates main" \
		> /etc/apt/sources.list; \
	apt-get update; \
	apt-get -y dist-upgrade; \
	apt-get -y install qemu-user-static;

ARG MDVL_CI_ARCH_PREFIX=
ARG MDVL_CI_DEBIAN_VERSION=buster
FROM ${MDVL_CI_ARCH_PREFIX}debian:$MDVL_CI_DEBIAN_VERSION
ARG MDVL_CI_DEBIAN_VERSION=buster
LABEL maintainer "Linux-Fan, Ma_Sys.ma <Ma_Sys.ma@web.de>"
LABEL name masysmaci
ARG MA_DEBIAN_MIRROR=http://ftp.it.debian.org/debian
SHELL ["/bin/sh", "-ec"]
COPY --from=qemustatic /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static
# TODO z currently these are three layers for faster debugging.
#        Once the container works as expected, replace by just one.
RUN     :; \
	printf "%s\n%s\n%s %s\n" \
		"deb $MA_DEBIAN_MIRROR $MDVL_CI_DEBIAN_VERSION main" \
		"deb $MA_DEBIAN_MIRROR $MDVL_CI_DEBIAN_VERSION-updates main" \
		"deb http://security.debian.org/" \
					"$MDVL_CI_DEBIAN_VERSION/updates main" \
		> /etc/apt/sources.list; \
	useradd -u 1000 -m masysmaci; \
	apt-get update; \
	apt-get -y dist-upgrade; \
	:
RUN     :; \
	apt-get -y install openssh-server reprepro \
			ant ant-optional libxz-java openjdk-11-jdk \
			libxml-dom-perl libgit-wrapper-perl \
			libgit-repository-perl p7zip-full \
			libfile-copy-recursive-perl libproc-simple-perl \
			config-package-dev gcc g++ gnat devscripts \
			libidn11-dev libgcrypt20-dev libgnutls28-dev \
			libncurses-dev libxml2-dev; \
	:
RUN     :; \
	mkdir /home/masysmaci/sshd; \
	cp /etc/ssh/ssh_host_ed25519_key /home/masysmaci/sshd; \
	printf "%s\n%s\n" \
		"Port 2222" \
		"HostKey /home/masysmaci/sshd/ssh_host_ed25519_key" \
		> /home/masysmaci/sshd/sshd_config; \
	chown -R masysmaci:masysmaci /home/masysmaci; \
	chmod 600 /home/masysmaci/sshd/*; \
	:
USER masysmaci
CMD ["/usr/sbin/sshd", "-f", "/home/masysmaci/sshd/sshd_config", "-D"]
