version: "2"
services:
    i386:
        image: i368/masysmaci
        build:
            context: .
            dockerfile: dockerfile_masysmaci
            args:
                - MDVL_CI_ARCH_PREFIX=i386/
                - MA_DEBIAN_MIRROR=$MA_DEBIAN_MIRROR
        volume:
            - ./dot_ssh_server:/home/masysmaci/.ssh:ro
            - ../:/home/masysmaci/root
